
# Uncomment this line to define a global platform for your project
# platform :ios, '8.3'

# ignore all warnings from all pods
inhibit_all_warnings!
# Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it.
use_frameworks!

target 'iChatWithXMPP' do
    pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
end

